services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      JWT_SECRET: secret_token
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: pleasure749%
      DB_NAME: munch_dev
      SMTP_SERVICE: gmail
      SMTP_PORT: 465
      SMTP_PASSWORD: "wyukllmhqcuchmnn"
      SMTP_MAIL: "zerotickets.info@gmail.com"
    depends_on:
      - db

  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pleasure749%
      MYSQL_DATABASE: munch_dev
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
